import {UpdateHistory} from './update-history';

export interface CustomerModel{
    id : string;
    name : string;
    phone : string;
    email : string;
    school : string;
    created_time : Date;
    modified_time : Date;
    created_by : string;
    modified_by : string;
    name_cmnd : string;
    cmnd : string;
    birthday : Date;
    place_of_birth : string;
    permanent_address : string;
    current_residence : string;
    word_place : string;
    career : string;
    career_other : string;
    work_position : string;
    work_position_other : string;
    image_cmnd : string;
    contact_time : Date;
    card_address : string;
    card_template : string;
    place_of_birth_city : string;
    place_of_birth_county : string;
    place_of_birth_ward : string;
    permanent_address_city : string;
    permanent_address_county : string;
    permanent_address_ward : string;
    current_residence_city : string;
    current_residence_county : string;
    current_residence_ward : string;
    credit_score : string;
    submit_time : string;
    approve_time : string;
    change_reason : string;
    status : string;
    msb_card_used : boolean;
    customer_type : string;
    handle_time: Date;
    name_in_card: string;
    staff_handle: string;
    staff_handle_id: string;
    history: UpdateHistory[];
}