/*
CREATE TABLE "F9_APP_INSIGHT"."FRIEND_SCHOOL_3"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "SCHOOL_3_ID" INTEGER NOT NULL, 
    "TOTAL_SIZES" INTEGER, 
    "TOTAL_LINKS" INTEGER)   
   COMPRESS YES STATIC  
   DISTRIBUTE BY HASH("FACEBOOK_ID", "SCHOOL_3_ID")   
     IN "USERSPACE1"  
   ORGANIZE BY ROW  ;
ALTER TABLE "F9_APP_INSIGHT"."FRIEND_SCHOOL_3" ADD PRIMARY KEY ("FACEBOOK_ID", "SCHOOL_3_ID") ENFORCED ;
CREATE INDEX FRIEND_SCHOOL_3_SCHOOL_3_ID_IDX ON F9_APP_INSIGHT.FRIEND_SCHOOL_3 (SCHOOL_3_ID);
CREATE INDEX FRIEND_SCHOOL_3_FACEBOOK_ID_IDX ON F9_APP_INSIGHT.FRIEND_SCHOOL_3 (FACEBOOK_ID);
CREATE INDEX FRIEND_SCHOOL_3_TOTAL_SIZES_IDX ON F9_APP_INSIGHT.FRIEND_SCHOOL_3 (TOTAL_SIZES);
*/

/*
INSERT INTO F9_APP_INSIGHT.FRIEND_SCHOOL_3(FACEBOOK_ID,SCHOOL_3_ID,TOTAL_SIZES) 
SELECT c.id1 AS "FACEBOOK_ID",a.school_3_id AS "SCHOOL_3_ID",count(*) AS "TOTAL_SIZES" FROM F9_APP_INSIGHT.user_school_3 a
INNER JOIN F9_APP_INSIGHT.user_friend c ON a.facebook_id = c.id2
INNER JOIN F9_APP_INSIGHT.user_profile p ON c.id1 = p.facebook_id
GROUP BY c.id1,a.school_3_id HAVING count(*) > 5
*/