/*
CREATE TABLE "F9_APP_INSIGHT"."FRIEND_COLLEGE"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "COLLEGE_ID" INTEGER NOT NULL, 
    "TOTAL_SIZES" INTEGER, 
    "TOTAL_LINKS" INTEGER)   
   COMPRESS YES STATIC  
   DISTRIBUTE BY HASH("FACEBOOK_ID", "COLLEGE_ID")   
     IN "USERSPACE1"  
   ORGANIZE BY ROW  ;
ALTER TABLE "F9_APP_INSIGHT"."FRIEND_COLLEGE" ADD PRIMARY KEY ("FACEBOOK_ID", "COLLEGE_ID") ENFORCED ;
CREATE INDEX FRIEND_COLLEGE_COLLEGE_ID_IDX ON F9_APP_INSIGHT.FRIEND_COLLEGE (COLLEGE_ID);
CREATE INDEX FRIEND_COLLEGE_FACEBOOK_ID_IDX ON F9_APP_INSIGHT.FRIEND_COLLEGE (FACEBOOK_ID);
CREATE INDEX FRIEND_COLLEGE_TOTAL_SIZES_IDX ON F9_APP_INSIGHT.FRIEND_COLLEGE (TOTAL_SIZES);
*/

/*
INSERT INTO F9_APP_INSIGHT.FRIEND_COLLEGE(FACEBOOK_ID,COLLEGE_ID,TOTAL_SIZES) 
SELECT c.id1 AS "FACEBOOK_ID",a.college_id AS "COLLEGE_ID",count(*) AS "TOTAL_SIZES" FROM F9_APP_INSIGHT.user_college a
INNER JOIN F9_APP_INSIGHT.user_friend c ON a.facebook_id = c.id2
INNER JOIN F9_APP_INSIGHT.user_profile p ON c.id1 = p.facebook_id
GROUP BY c.id1,a.college_id HAVING count(*) > 5
*/