/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_NATION*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_NATION"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "TYPE" VARCHAR(20 OCTETS) NOT NULL,
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_NATION" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","TYPE") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_NATION_NATION_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_NATION (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_NATION_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_NATION (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_NATION_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_NATION (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_NATION_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_NATION (TYPE);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_NATION_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_NATION (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_NATION_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_NATION (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_NATION_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_NATION (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_NATION*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_REGILION*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_REGILION"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "TYPE" VARCHAR(20 OCTETS) NOT NULL,
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_REGILION" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","TYPE") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_REGILION_REGILION_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_REGILION (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_REGILION_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_REGILION (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_REGILION_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_REGILION (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_REGILION_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_REGILION (TYPE);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_REGILION_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_REGILION (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_REGILION_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_REGILION (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_REGILION_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_REGILION (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_REGILION*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_LANGUAGES*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_LANGUAGES"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_LANGUAGES" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_LANGUAGES_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_LANGUAGES (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_LANGUAGES_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_LANGUAGES (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_LANGUAGES_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_LANGUAGES (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_LANGUAGES_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_LANGUAGES (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_LANGUAGES_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_LANGUAGES (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_LANGUAGES_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_LANGUAGES (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_LANGUAGES*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_LANGUAGES*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_LANGUAGES"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_LANGUAGES" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_LANGUAGES_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_LANGUAGES (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_LANGUAGES_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_LANGUAGES (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_LANGUAGES_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_LANGUAGES (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_LANGUAGES_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_LANGUAGES (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_LANGUAGES_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_LANGUAGES (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_LANGUAGES_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_LANGUAGES (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_LANGUAGES*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_HOMETOWN_LOCATION*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_HOMETOWN_LOCATION"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_HOMETOWN_LOCATION" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_HOMETOWN_LOCATION_HOMETOWN_LOCATION_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_HOMETOWN_LOCATION (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_HOMETOWN_LOCATION_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_HOMETOWN_LOCATION (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_HOMETOWN_LOCATION_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_HOMETOWN_LOCATION (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_HOMETOWN_LOCATION_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_HOMETOWN_LOCATION (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_HOMETOWN_LOCATION_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_HOMETOWN_LOCATION (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_HOMETOWN_LOCATION_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_HOMETOWN_LOCATION (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_HOMETOWN_LOCATION*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_HOMETOWN*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_HOMETOWN"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_HOMETOWN" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_HOMETOWN_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_HOMETOWN (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_HOMETOWN_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_HOMETOWN (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_HOMETOWN_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_HOMETOWN (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_HOMETOWN_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_HOMETOWN (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_HOMETOWN_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_HOMETOWN (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_HOMETOWN_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_HOMETOWN (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_HOMETOWN*/



/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_COMPANY*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_COMPANY"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_COMPANY" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COMPANY_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COMPANY (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COMPANY_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COMPANY (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COMPANY_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COMPANY (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COMPANY_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COMPANY (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COMPANY_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COMPANY (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_COMPANY*/


/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_WORK_COMPANY*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_WORK_COMPANY"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_WORK_COMPANY" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_WORK_COMPANY_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_COMPANY (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_WORK_COMPANY_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_COMPANY (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_WORK_COMPANY_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_COMPANY (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_WORK_COMPANY_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_COMPANY (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_WORK_COMPANY_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_COMPANY (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_WORK_COMPANY*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_INTEREST*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_INTEREST";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_INTEREST"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	"TYPE" VARCHAR(20 OCTETS) NOT NULL
	"UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_INTEREST" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","TYPE") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_INTEREST_INTEREST_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_INTEREST (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_INTEREST_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_INTEREST (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_INTEREST_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_INTEREST (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_INTEREST_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_INTEREST (TYPE);
CREATE INDEX FACEBOOK_INSIGHT_INTEREST_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_INTEREST (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_INTEREST_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_INTEREST (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_INTEREST_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_INTEREST (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_INTEREST*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_EDUCATION_COLLEGE*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_COLLEGE";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_COLLEGE"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	  "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_COLLEGE" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_COLLEGE_COLLEGE_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_COLLEGE (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_COLLEGE_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_COLLEGE (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_COLLEGE_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_COLLEGE (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_COLLEGE_FACEBOOK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_COLLEGE (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_COLLEGE_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_COLLEGE (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_COLLEGE_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_COLLEGE (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_EDUCATION_COLLEGE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_COLLEGE*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_COLLEGE";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_COLLEGE"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	  "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_COLLEGE" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COLLEGE_COLLEGE_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COLLEGE (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COLLEGE_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COLLEGE (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COLLEGE_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COLLEGE (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COLLEGE_FACEBOOK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COLLEGE (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COLLEGE_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COLLEGE (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_COLLEGE_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COLLEGE (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_COLLEGE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_SCHOOL_1*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_1";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_1"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	  "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("REF_ID","SOURCE_ID","KEYWORD") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_1" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_1_SCHOOL_1_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_1 (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_1_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_1 (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_1_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_1 (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_1_FACEBOOK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_1 (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_1_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_1 (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_1_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_1 (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_SCHOOL_1*/


/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	  "EDUCATION_SCHOOL" BOOLEAN,
	  "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("REF_ID","SOURCE_ID","KEYWORD") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1_SCHOOL_1_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1 (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1 (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1 (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1_FACEBOOK_EDUCATION_SCHOOL_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1 (EDUCATION_SCHOOL);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1_FACEBOOK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1 (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1 (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1 (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_SCHOOL_2*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_2";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_2"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	  "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("REF_ID","SOURCE_ID","KEYWORD") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_2" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_2_SCHOOL_2_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_2 (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_2_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_2 (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_2_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_2 (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_2_FACEBOOK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_2 (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_2_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_2 (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_2_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_2 (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_SCHOOL_2*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	  "EDUCATION_SCHOOL" BOOLEAN,
	  "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("REF_ID","SOURCE_ID","KEYWORD") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2_SCHOOL_2_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2 (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2 (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2 (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2_FACEBOOK_EDUCATION_SCHOOL_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2 (EDUCATION_SCHOOL);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2_FACEBOOK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2 (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2 (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2 (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	  "EDUCATION_SCHOOL" BOOLEAN,
	  "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("REF_ID","SOURCE_ID","KEYWORD") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3_SCHOOL_3_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3 (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3 (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3 (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3_FACEBOOK_EDUCATION_SCHOOL_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3 (EDUCATION_SCHOOL);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3_FACEBOOK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3 (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3 (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3 (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_SCHOOL_3*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_3";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_3"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
	  "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("REF_ID","SOURCE_ID","KEYWORD") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_SCHOOL_3" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_3_SCHOOL_3_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_3 (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_3_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_3 (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_3_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_3 (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_3_FACEBOOK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_3 (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_3_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_3 (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_SCHOOL_3_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_3 (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_SCHOOL_3*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_JOB*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_JOB"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_JOB" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_JOB_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_JOB (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_JOB_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_JOB (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_JOB_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_JOB (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_JOB_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_JOB (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_JOB_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_JOB (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_JOB*/


/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_WORK_JOB*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_WORK_JOB"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_WORK_JOB" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_WORK_JOB_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_JOB (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_WORK_JOB_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_JOB (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_WORK_JOB_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_JOB (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_WORK_JOB_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_JOB (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_WORK_JOB_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_JOB (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_WORK_JOB_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_JOB (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_WORK_JOB*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_RANK*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_RANK"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_RANK" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_RANK_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_RANK (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_RANK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_RANK (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_RANK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_RANK (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_RANK_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_RANK (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_RANK_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_RANK (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_RANK*/


/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_WORK_RANK*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_WORK_RANK"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_WORK_RANK" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_WORK_RANK_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_RANK (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_WORK_RANK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_RANK (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_WORK_RANK_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_RANK (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_WORK_RANK_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_RANK (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_WORK_RANK_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_RANK (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_WORK_RANK_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_WORK_RANK (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_WORK_RANK*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_KEYWORD_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE (KEYWORD);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "UNI_KEY" VARCHAR(1000 OCTETS) NOT NULL,
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("SOURCE_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD_REF_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD (REF_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD (SOURCE_ID);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD_UNI_KEY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD (UNI_KEY);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD_CREATED_TIME_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD (CREATED_TIME);
CREATE INDEX FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD_CREATED_BY_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD (CREATED_BY);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_GROUP_BEHAVIOR_TYPE_NOT_KEYWORD*/



/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_USER_STICKER*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_USER_STICKER"  (
    "FACEBOOK_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "STICKER_ID" INTEGER NOT NULL , 
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) 
  COMPRESS YES STATIC 
  DISTRIBUTE BY HASH("FACEBOOK_ID") 
  IN "USERSPACE1" 
  ORGANIZE BY ROW 
  NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_USER_STICKER" ADD PRIMARY KEY  ("FACEBOOK_ID") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_USER_STICKER_STICKER_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_USER_STICKER (STICKER_ID);
CREATE INDEX FACEBOOK_INSIGHT_USER_STICKER_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_USER_STICKER (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_USER_STICKER*/



/*BEGIN F9_STG_INSIGHT FACEBOOK_INSIGHT_USER_STICKER*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_USER_STICKER_ALL"  (
    "FACEBOOK_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "STICKER_ID" INTEGER NOT NULL , 
    "UNI_KEY" VARCHAR(40 OCTETS) NOT NULL , 
    "CREATED_TIME" INTEGER,
    "CREATED_BY" INTEGER
  ) 
  COMPRESS YES STATIC 
  DISTRIBUTE BY HASH("FACEBOOK_ID") 
  IN "USERSPACE1" 
  ORGANIZE BY ROW 
  NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_INSIGHT_USER_STICKER_ALL" ADD PRIMARY KEY  ("UNI_KEY") ENFORCED ;
CREATE INDEX FACEBOOK_INSIGHT_USER_STICKER_ALL_STICKER_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_USER_STICKER_ALL (STICKER_ID);
CREATE INDEX FACEBOOK_INSIGHT_USER_STICKER_ALL_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_INSIGHT_USER_STICKER_ALL (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_INSIGHT_USER_STICKER*/