/* BEGIN REF_AGE */
DROP TABLE "F9_STG_INSIGHT"."REF_AGE";
CREATE TABLE "F9_STG_INSIGHT"."REF_AGE"  (
		  "ID" VARCHAR(50 OCTETS)  NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_AGE"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_AGE */

/* BEGIN REF_GENDER */
DROP TABLE "F9_STG_INSIGHT"."REF_GENDER";
CREATE TABLE "F9_STG_INSIGHT"."REF_GENDER"  (
		  "ID" VARCHAR(50 OCTETS)  NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_GENDER"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_GENDER */

/* BEGIN REF_RELATIONSHIP_STATUS */
DROP TABLE "F9_STG_INSIGHT"."REF_RELATIONSHIP_STATUS";
CREATE TABLE "F9_STG_INSIGHT"."REF_RELATIONSHIP_STATUS"  (
		  "ID" VARCHAR(50 OCTETS) NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_RELATIONSHIP_STATUS"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_RELATIONSHIP_STATUS */

/* BEGIN REF_TOWN */
DROP TABLE "F9_STG_INSIGHT"."REF_TOWN";
CREATE TABLE "F9_STG_INSIGHT"."REF_TOWN"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_TOWN"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_TOWN */

/* BEGIN REF_DOMAIN */
DROP TABLE "F9_STG_INSIGHT"."REF_DOMAIN";
CREATE TABLE "F9_STG_INSIGHT"."REF_DOMAIN"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_DOMAIN"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_DOMAIN */

/* BEGIN REF_CITY */
DROP TABLE "F9_STG_INSIGHT"."REF_CITY";
CREATE TABLE "F9_STG_INSIGHT"."REF_CITY"  (
		  "ID" BIGINT NOT NULL , 
		  "PID" INTEGER , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "DOMAIN_ID" INTEGER , 
		  "TOWN_ID" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_CITY"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_CITY */

/* BEGIN REF_NATION */
DROP TABLE "F9_STG_INSIGHT"."REF_NATION";
CREATE TABLE "F9_STG_INSIGHT"."REF_NATION"  (
		  "ID" INTEGER NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_NATION"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_NATION */

/* BEGIN REF_REGILION */
DROP TABLE "F9_STG_INSIGHT"."REF_REGILION";
CREATE TABLE "F9_STG_INSIGHT"."REF_REGILION"  (
		  "ID" INTEGER NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "CREATED_TIME" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_REGILION"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_REGILION */

/* BEGIN REF_LANGUAGES */
DROP TABLE "F9_STG_INSIGHT"."REF_LANGUAGES";
CREATE TABLE "F9_STG_INSIGHT"."REF_LANGUAGES"  (
		  "ID" INTEGER NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_LANGUAGES"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_LANGUAGES */



/* BEGIN REF_INTEREST */
DROP TABLE "F9_STG_INSIGHT"."REF_INTEREST";
CREATE TABLE "F9_STG_INSIGHT"."REF_INTEREST"  (
		  "ID" BIGINT NOT NULL , 
		  "PID" INTEGER , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "DISPLAY_NAME" VARCHAR(1000 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "LEVEL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_INTEREST"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_INTEREST */


/* BEGIN REF_COMPANY */
DROP TABLE "F9_STG_INSIGHT"."REF_COMPANY";
CREATE TABLE "F9_STG_INSIGHT"."REF_COMPANY"  (
		  "ID" BIGINT NOT NULL , 
		  "COMPANY_BLOCK_ID" INTEGER , 
		  "COMPANY_SCALE_ID" INTEGER , 
		  "COMPANY_FIELD_ID" INTEGER , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "DISPLAY_NAME" VARCHAR(1000 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_COMPANY"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_COMPANY */

/* BEGIN REF_COMPANY_BLOCK */
DROP TABLE "F9_STG_INSIGHT"."REF_COMPANY_BLOCK";
CREATE TABLE "F9_STG_INSIGHT"."REF_COMPANY_BLOCK"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "PID" INTEGER , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_COMPANY_BLOCK"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_COMPANY_BLOCK */

/* BEGIN REF_COMPANY_FIELD */
DROP TABLE "F9_STG_INSIGHT"."REF_COMPANY_FIELD";
CREATE TABLE "F9_STG_INSIGHT"."REF_COMPANY_FIELD"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_COMPANY_FIELD"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_COMPANY_FIELD */

/* BEGIN REF_COMPANY_SCALE */
DROP TABLE "F9_STG_INSIGHT"."REF_COMPANY_SCALE";
CREATE TABLE "F9_STG_INSIGHT"."REF_COMPANY_SCALE"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_COMPANY_SCALE"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_COMPANY_SCALE */

/* BEGIN REF_TOWN */
DROP TABLE "F9_STG_INSIGHT"."REF_TOWN";
CREATE TABLE "F9_STG_INSIGHT"."REF_TOWN"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_TOWN"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_TOWN */

/* BEGIN REF_DOMAIN */
DROP TABLE "F9_STG_INSIGHT"."REF_DOMAIN";
CREATE TABLE "F9_STG_INSIGHT"."REF_DOMAIN"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_DOMAIN"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_DOMAIN */

/* BEGIN REF_SCHOOL_1 */
DROP TABLE "F9_STG_INSIGHT"."REF_SCHOOL_1";
CREATE TABLE "F9_STG_INSIGHT"."REF_SCHOOL_1"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "DISPLAY_NAME" VARCHAR(1000 OCTETS) NOT NULL , 
		  "CITY_ID" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_SCHOOL_1"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_SCHOOL_1 */

/* BEGIN REF_SCHOOL_2 */
DROP TABLE "F9_STG_INSIGHT"."REF_SCHOOL_2";
CREATE TABLE "F9_STG_INSIGHT"."REF_SCHOOL_2"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "DISPLAY_NAME" VARCHAR(1000 OCTETS) NOT NULL , 
		  "CITY_ID" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_SCHOOL_2"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_SCHOOL_2 */

/* BEGIN REF_SCHOOL_3 */
DROP TABLE "F9_STG_INSIGHT"."REF_SCHOOL_3";
CREATE TABLE "F9_STG_INSIGHT"."REF_SCHOOL_3"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "DISPLAY_NAME" VARCHAR(1000 OCTETS) NOT NULL , 
		  "CITY_ID" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_SCHOOL_3"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_SCHOOL_3 */

/* BEGIN REF_COLLEGE */
DROP TABLE "F9_STG_INSIGHT"."REF_COLLEGE";
CREATE TABLE "F9_STG_INSIGHT"."REF_COLLEGE"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(1000 OCTETS) NOT NULL , 
		  "DISPLAY_NAME" VARCHAR(1000 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CITY_ID" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_COLLEGE"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_COLLEGE */

/* BEGIN REF_CAREER */
DROP TABLE "F9_STG_INSIGHT"."REF_CAREER";
CREATE TABLE "F9_STG_INSIGHT"."REF_CAREER"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_CAREER"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_CAREER */

/* BEGIN REF_JOB */
DROP TABLE "F9_STG_INSIGHT"."REF_JOB";
CREATE TABLE "F9_STG_INSIGHT"."REF_JOB"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "CAREER_ID" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_JOB"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_JOB */

/* BEGIN REF_RANK */
DROP TABLE "F9_STG_INSIGHT"."REF_RANK";
CREATE TABLE "F9_STG_INSIGHT"."REF_RANK"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "AGE_FROM" INTEGER , 
		  "AGE_TO" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_RANK"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_RANK */

/* BEGIN REF_BEHAVIOR_TYPE */
DROP TABLE "F9_STG_INSIGHT"."REF_BEHAVIOR_TYPE";
CREATE TABLE "F9_STG_INSIGHT"."REF_BEHAVIOR_TYPE"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "GLOBAL" INTEGER , 
		  "INCOME_ID" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_BEHAVIOR_TYPE"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_BEHAVIOR_TYPE */

/* BEGIN REF_INCOME */
DROP TABLE "F9_STG_INSIGHT"."REF_INCOME";
CREATE TABLE "F9_STG_INSIGHT"."REF_INCOME"  (
		  "ID" BIGINT NOT NULL , 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "TEXT_SEARCH" VARCHAR(255 OCTETS) NOT NULL , 
		  "MIN" INTEGER , 
		  "MAX" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_INCOME"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_INCOME */

/* BEGIN REF_NON_MANAGER */
DROP TABLE "F9_STG_INSIGHT"."REF_NON_MANAGER";
CREATE TABLE "F9_STG_INSIGHT"."REF_NON_MANAGER"  (
		  "ID" BIGINT NOT NULL , 
		  "COMPANY_BLOCK_ID" INTEGER , 
		  "FIELD_ID" INTEGER , 
		  "SCALE_ID" INTEGER , 
		  "JOB_ID" INTEGER , 
		  "RANK_ID" INTEGER , 
		  "TOWN_ID" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "INCOME_ID" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_NON_MANAGER"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_NON_MANAGER */

/* BEGIN REF_MANAGER */
DROP TABLE "F9_STG_INSIGHT"."REF_MANAGER";
CREATE TABLE "F9_STG_INSIGHT"."REF_MANAGER"  (
		  "ID" BIGINT NOT NULL , 
		  "COMPANY_BLOCK_ID" INTEGER , 
		  "FIELD_ID" INTEGER , 
		  "SCALE_ID" INTEGER , 
		  "JOB_ID" INTEGER , 
		  "RANK_ID" INTEGER , 
		  "TOWN_ID" INTEGER , 
		  "GLOBAL" INTEGER , 
		  "INCOME_ID" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_MANAGER"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_MANAGER */

/* BEGIN REF_COST */
DROP TABLE "F9_STG_INSIGHT"."REF_COST";
CREATE TABLE "F9_STG_INSIGHT"."REF_COST"  (
		  "ID" BIGINT NOT NULL , 
		  "BEHAVIOR_TYPE_ID" INTEGER , 
		  "NAME" VARCHAR(255 OCTETS) , 
		  "GLOBAL" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_COST"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END REF_COST */

/* BEGIN REF_STICKER */
DROP TABLE "F9_STG_INSIGHT"."REF_STICKER";
CREATE TABLE "F9_STG_INSIGHT"."REF_STICKER"  (
		  "ID" BIGINT NOT NULL , 
		  "FACEBOOK_ID" VARCHAR(20 OCTETS) , 
		  "GLOBAL" INTEGER , 
		  "STICKER_TYPE" INTEGER , 
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_STICKER"  ADD PRIMARY KEY ("ID") ENFORCED ;
CREATE INDEX REF_STICKER_STICKER_TYPE_IDX ON F9_APP_INSIGHT.REF_STICKER (STICKER_TYPE);
/* END REF_STICKER */