/* BEGIN JOB_TYPE */
DROP TABLE "F9_APP_CYBER_INSIGHT"."JOB_TYPE";
CREATE TABLE "F9_APP_CYBER_INSIGHT"."JOB_TYPE"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
          "DB_MONGO" VARCHAR(255 OCTETS) NOT NULL,
          "DB_COLLECTION" VARCHAR(255 OCTETS)  NOT NULL,
          "CRAWLER_TYPE" VARCHAR(255 OCTETS) NOT NULL,
          "IS_PAGE" INTEGER DEFAULT 0,
		  "PRIORITY" INTEGER NOT NULL,
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_APP_CYBER_INSIGHT"."JOB_TYPE"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END JOB_TYPE */

/* BEGIN JOB */
DROP TABLE "F9_APP_CYBER_INSIGHT"."JOB";
CREATE TABLE "F9_APP_CYBER_INSIGHT"."JOB"  (
		  "ID" INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 
          "SOURCE_TYPE" VARCHAR(20 OCTETS) NOT NULL,
          "GROUP" VARCHAR(255 OCTETS),
          "SQL" CLOB(32000 OCTETS),
          "BATCH_LIMIT" INTEGER NOT NULL,
          "MULTI_LIMIT" INTEGER NOT NULL,
		  "START_TIME" INTEGER,
		  "FINISH_TIME" INTEGER,
		  "STATUS" VARCHAR(255 OCTETS) NOT NULL,
		  "PRIORITY" INTEGER NOT NULL,
		  "CREATED_TIME" INTEGER , 
		  "IS_DELETE" INTEGER , 
		  "CREATED_BY" INTEGER , 
		  "MODIFIED_TIME" INTEGER , 
		  "MODIFIED_BY" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_APP_CYBER_INSIGHT"."JOB"  ADD PRIMARY KEY ("ID") ENFORCED ;
/* END JOB */

/* BEGIN JOB_JOB_TYPE_MUL */
DROP TABLE "F9_APP_CYBER_INSIGHT"."JOB_JOB_TYPE_MUL";
CREATE TABLE "F9_APP_CYBER_INSIGHT"."JOB_JOB_TYPE_MUL"  (
		  "ID" INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
		  "JOB_ID" INTEGER  NOT NULL ,
		  "JOB_TYPE_ID" INTEGER NOT NULL,
          "STATUS" VARCHAR(20 OCTETS) NOT NULL,
		  "CREATED_TIME" INTEGER , 
		  "START_TIME" INTEGER , 
		  "FINISH_TIME" INTEGER, 
		  "MODIFIED_TIME" INTEGER )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("JOB_ID","JOB_TYPE_ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_APP_CYBER_INSIGHT"."JOB_JOB_TYPE_MUL"  ADD PRIMARY KEY ("JOB_ID","JOB_TYPE_ID") ENFORCED ;
CREATE INDEX JOB_JOB_TYPE_MUL_JOB_ID_IDX ON F9_APP_CYBER_INSIGHT.JOB_JOB_TYPE_MUL (JOB_ID);
CREATE INDEX JOB_JOB_TYPE_MUL_JOB_TYPE_ID_IDX ON F9_APP_CYBER_INSIGHT.JOB_JOB_TYPE_MUL (JOB_TYPE_ID);
CREATE INDEX JOB_JOB_TYPE_MUL_STATUS_IDX ON F9_APP_CYBER_INSIGHT.JOB_JOB_TYPE_MUL (STATUS);
/* END JOB_JOB_TYPE_MUL */


/* BEGIN JOB_DETAIL */
DROP TABLE "F9_APP_CYBER_INSIGHT"."JOB_DETAIL";
CREATE TABLE "F9_APP_CYBER_INSIGHT"."JOB_DETAIL"  (
		  "ID" INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
		  "JOB_JOB_TYPE_MUL_ID" INTEGER  NOT NULL ,
		  "OBJECT_ID" VARCHAR(16 OCTETS) NOT NULL,
		  "STATUS" INTEGER NOT NULL,
		  "CREATED_TIME" INTEGER , 
		  "FINISH_TIME" INTEGER 
	  )   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("OBJECT_ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_APP_CYBER_INSIGHT"."JOB_DETAIL"  ADD PRIMARY KEY ("JOB_JOB_TYPE_MUL_ID","OBJECT_ID") ENFORCED ;
CREATE INDEX JOB_DETAIL_JOB_JOB_TYPE_MUL_ID_IDX ON F9_APP_CYBER_INSIGHT.JOB_DETAIL (JOB_JOB_TYPE_MUL_ID);
CREATE INDEX JOB_DETAIL_OBJECT_ID_IDX ON F9_APP_CYBER_INSIGHT.JOB_DETAIL (OBJECT_ID);
CREATE INDEX JOB_DETAIL_STATUS_IDX ON F9_APP_CYBER_INSIGHT.JOB_DETAIL (STATUS);
/* END JOB_DETAIL */