/* BEGIN REF_NATION_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_NATION_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_NATION_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_NATION_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_NATION_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_NATION_KEYWORD_MAPPING (ID);
CREATE INDEX REF_NATION_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_NATION_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_NATION_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_NATION_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_NATION_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_NATION_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_NATION_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_NATION_KEYWORD_MAPPING (CREATED_BY);
/* END REF_NATION_KEYWORD_MAPPING */


/* BEGIN REF_REGILION_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_REGILION_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_REGILION_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_REGILION_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_REGILION_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_REGILION_KEYWORD_MAPPING (ID);
CREATE INDEX REF_REGILION_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_REGILION_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_REGILION_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_REGILION_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_REGILION_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_REGILION_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_REGILION_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_REGILION_KEYWORD_MAPPING (CREATED_BY);
/* END REF_REGILION_KEYWORD_MAPPING */


/* BEGIN REF_LANGUAGES_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_LANGUAGES_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_LANGUAGES_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_LANGUAGES_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_LANGUAGES_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_MAPPING (ID);
CREATE INDEX REF_LANGUAGES_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_LANGUAGES_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_LANGUAGES_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_LANGUAGES_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_MAPPING (CREATED_BY);
/* END REF_LANGUAGES_KEYWORD_MAPPING */


/* BEGIN REF_LANGUAGES_KEYWORD_LANGUAGE */
DROP TABLE "F9_STG_INSIGHT"."REF_LANGUAGES_KEYWORD_LANGUAGE";
CREATE TABLE "F9_STG_INSIGHT"."REF_LANGUAGES_KEYWORD_LANGUAGE"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_LANGUAGES_KEYWORD_LANGUAGE"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_LANGUAGES_KEYWORD_LANGUAGE_ID_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_LANGUAGE (ID);
CREATE INDEX REF_LANGUAGES_KEYWORD_LANGUAGE_KEYWORD_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_LANGUAGE (KEYWORD);
CREATE INDEX REF_LANGUAGES_KEYWORD_LANGUAGE_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_LANGUAGE (UNI_KEY);
CREATE INDEX REF_LANGUAGES_KEYWORD_LANGUAGE_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_LANGUAGE (CREATED_TIME);
CREATE INDEX REF_LANGUAGES_KEYWORD_LANGUAGE_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_LANGUAGES_KEYWORD_LANGUAGE (CREATED_BY);
/* END REF_LANGUAGES_KEYWORD_LANGUAGE */

/* BEGIN REF_CITY_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_CITY_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_CITY_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_CITY_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_CITY_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_CITY_KEYWORD_MAPPING (ID);
CREATE INDEX REF_CITY_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_CITY_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_CITY_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_CITY_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_CITY_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_CITY_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_CITY_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_CITY_KEYWORD_MAPPING (CREATED_BY);
/* END REF_CITY_KEYWORD_MAPPING */

/* BEGIN REF_INTEREST_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_INTEREST_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_INTEREST_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_INTEREST_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_INTEREST_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_INTEREST_KEYWORD_MAPPING (ID);
CREATE INDEX REF_INTEREST_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_INTEREST_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_INTEREST_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_INTEREST_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_INTEREST_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_INTEREST_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_INTEREST_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_INTEREST_KEYWORD_MAPPING (CREATED_BY);
/* END REF_INTEREST_KEYWORD_MAPPING */

/* BEGIN REF_SCHOOL_1_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_SCHOOL_1_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_SCHOOL_1_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_SCHOOL_1_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_SCHOOL_1_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_SCHOOL_1_KEYWORD_MAPPING (ID);
CREATE INDEX REF_SCHOOL_1_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_SCHOOL_1_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_SCHOOL_1_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_SCHOOL_1_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_SCHOOL_1_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_SCHOOL_1_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_SCHOOL_1_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_SCHOOL_1_KEYWORD_MAPPING (CREATED_BY);
/* END REF_SCHOOL_1_KEYWORD_MAPPING */

/* BEGIN REF_SCHOOL_2_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_SCHOOL_2_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_SCHOOL_2_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_SCHOOL_2_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_SCHOOL_2_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_SCHOOL_2_KEYWORD_MAPPING (ID);
CREATE INDEX REF_SCHOOL_2_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_SCHOOL_2_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_SCHOOL_2_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_SCHOOL_2_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_SCHOOL_2_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_SCHOOL_2_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_SCHOOL_2_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_SCHOOL_2_KEYWORD_MAPPING (CREATED_BY);
/* END REF_SCHOOL_2_KEYWORD_MAPPING */

/* BEGIN REF_SCHOOL_3_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_SCHOOL_3_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_SCHOOL_3_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_SCHOOL_3_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_SCHOOL_3_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_SCHOOL_3_KEYWORD_MAPPING (ID);
CREATE INDEX REF_SCHOOL_3_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_SCHOOL_3_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_SCHOOL_3_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_SCHOOL_3_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_SCHOOL_3_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_SCHOOL_3_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_SCHOOL_3_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_SCHOOL_3_KEYWORD_MAPPING (CREATED_BY);
/* END REF_SCHOOL_3_KEYWORD_MAPPING */

/* BEGIN REF_COLLEGE_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_COLLEGE_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_COLLEGE_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "TYPE" VARCHAR(20 OCTETS), 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_COLLEGE_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_COLLEGE_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_COLLEGE_KEYWORD_MAPPING (ID);
CREATE INDEX REF_COLLEGE_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_COLLEGE_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_COLLEGE_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_COLLEGE_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_COLLEGE_KEYWORD_MAPPING_TYPE_IDX ON F9_STG_INSIGHT.REF_COLLEGE_KEYWORD_MAPPING (TYPE);
CREATE INDEX REF_COLLEGE_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_COLLEGE_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_COLLEGE_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_COLLEGE_KEYWORD_MAPPING (CREATED_BY);
/* END REF_COLLEGE_KEYWORD_MAPPING */

/* BEGIN REF_JOB_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_JOB_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_JOB_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL,
		  "CREATED_TIME" INTEGER,
		  "CREATED_BY" INTEGER)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_JOB_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_JOB_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_JOB_KEYWORD_MAPPING (ID);
CREATE INDEX REF_JOB_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_JOB_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_JOB_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_JOB_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_JOB_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_JOB_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_JOB_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_JOB_KEYWORD_MAPPING (CREATED_BY);
/* END REF_JOB_KEYWORD_MAPPING */

/* BEGIN REF_RANK_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_RANK_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_RANK_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL,
		  "CREATED_TIME" INTEGER,
		  "CREATED_BY" INTEGER)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_RANK_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_RANK_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_RANK_KEYWORD_MAPPING (ID);
CREATE INDEX REF_RANK_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_RANK_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_RANK_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_RANK_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_RANK_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_RANK_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_RANK_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_RANK_KEYWORD_MAPPING (CREATED_BY);
/* END REF_RANK_KEYWORD_MAPPING */

/* BEGIN REF_BEHAVIOR_TYPE_KEYWORD_MAPPING */
DROP TABLE "F9_STG_INSIGHT"."REF_BEHAVIOR_TYPE_KEYWORD_MAPPING";
CREATE TABLE "F9_STG_INSIGHT"."REF_BEHAVIOR_TYPE_KEYWORD_MAPPING"  (
		  "ID" BIGINT NOT NULL , 
		  "KEYWORD" VARCHAR(255 OCTETS) NOT NULL, 
		  "UNI_KEY" VARCHAR(300 OCTETS) NOT NULL,
		  "CREATED_TIME" INTEGER,
		  "CREATED_BY" INTEGER)   
		 COMPRESS YES STATIC   DISTRIBUTE BY HASH("ID")    IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;;
ALTER TABLE "F9_STG_INSIGHT"."REF_BEHAVIOR_TYPE_KEYWORD_MAPPING"  ADD PRIMARY KEY ("ID","KEYWORD") ENFORCED ;
CREATE INDEX REF_BEHAVIOR_TYPE_KEYWORD_MAPPING_ID_IDX ON F9_STG_INSIGHT.REF_BEHAVIOR_TYPE_KEYWORD_MAPPING (ID);
CREATE INDEX REF_BEHAVIOR_TYPE_KEYWORD_MAPPING_KEYWORD_IDX ON F9_STG_INSIGHT.REF_BEHAVIOR_TYPE_KEYWORD_MAPPING (KEYWORD);
CREATE INDEX REF_BEHAVIOR_TYPE_KEYWORD_MAPPING_UNI_KEY_IDX ON F9_STG_INSIGHT.REF_BEHAVIOR_TYPE_KEYWORD_MAPPING (UNI_KEY);
CREATE INDEX REF_BEHAVIOR_TYPE_KEYWORD_MAPPING_CREATED_TIME_IDX ON F9_STG_INSIGHT.REF_BEHAVIOR_TYPE_KEYWORD_MAPPING (CREATED_TIME);
CREATE INDEX REF_BEHAVIOR_TYPE_KEYWORD_MAPPING_CREATED_BY_IDX ON F9_STG_INSIGHT.REF_BEHAVIOR_TYPE_KEYWORD_MAPPING (CREATED_BY);
/* END REF_BEHAVIOR_TYPE_KEYWORD_MAPPING */