/*BEGIN F9_STG_INSIGHT USER_INSIGHT_INTEREST*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_INTEREST";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_INTEREST"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
    "TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_INTEREST" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_INTEREST_INTEREST_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_INTEREST (REF_ID);
CREATE INDEX USER_INSIGHT_INTEREST_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_INTEREST (SOURCE_ID);
CREATE INDEX USER_INSIGHT_INTEREST_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_INTEREST (KEYWORD);
CREATE INDEX USER_INSIGHT_INTEREST_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_INTEREST (STATUS);
CREATE INDEX USER_INSIGHT_INTEREST_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_INTEREST (IS_DELETE);
CREATE INDEX USER_INSIGHT_INTEREST_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_INTEREST (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_INTEREST"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_INTEREST a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_INTEREST"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'PAGE' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_PAGE_INTEREST a
INNER JOIN "F9_APP_INSIGHT".USER_PAGE b ON a.SOURCE_ID = b.PAGE_ID;
/*END F9_STG_INSIGHT USER_INSIGHT_INTEREST*/

/*BEGIN F9_STG_INSIGHT USER_INSIGHT_COLLEGE*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_COLLEGE";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_COLLEGE"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_COLLEGE" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_COLLEGE_COLLEGE_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_COLLEGE (REF_ID);
CREATE INDEX USER_INSIGHT_COLLEGE_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_COLLEGE (SOURCE_ID);
CREATE INDEX USER_INSIGHT_COLLEGE_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_COLLEGE (KEYWORD);
CREATE INDEX USER_INSIGHT_COLLEGE_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_COLLEGE (STATUS);
CREATE INDEX USER_INSIGHT_COLLEGE_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_COLLEGE (IS_DELETE);
CREATE INDEX USER_INSIGHT_COLLEGE_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_COLLEGE (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_COLLEGE"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_COLLEGE a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_COLLEGE"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'EDUCATION' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_COLLEGE a
INNER JOIN "F9_STG_INSIGHT".FACEBOOK_USER_EDUCATION b ON a.SOURCE_ID = b.DATA;
/*END F9_STG_INSIGHT USER_INSIGHT_COLLEGE*/

/*BEGIN F9_STG_INSIGHT USER_INSIGHT_LANGUAGES*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_LANGUAGES";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_LANGUAGES"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_LANGUAGES" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_LANGUAGES_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LANGUAGES (REF_ID);
CREATE INDEX USER_INSIGHT_LANGUAGES_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LANGUAGES (SOURCE_ID);
CREATE INDEX USER_INSIGHT_LANGUAGES_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LANGUAGES (KEYWORD);
CREATE INDEX USER_INSIGHT_LANGUAGES_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LANGUAGES (STATUS);
CREATE INDEX USER_INSIGHT_LANGUAGES_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LANGUAGES (IS_DELETE);
CREATE INDEX USER_INSIGHT_LANGUAGES_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LANGUAGES (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_LANGUAGES"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_LANGUAGES a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_LANGUAGES"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'EDUCATION' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_LANGUAGES a
INNER JOIN "F9_STG_INSIGHT".FACEBOOK_USER_EDUCATION b ON a.SOURCE_ID = b.DATA;
/*END F9_STG_INSIGHT USER_INSIGHT_LANGUAGES*/

/*BEGIN F9_STG_INSIGHT USER_INSIGHT_HOMETOWN*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_HOMETOWN";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_HOMETOWN"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_HOMETOWN" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_HOMETOWN_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_HOMETOWN (REF_ID);
CREATE INDEX USER_INSIGHT_HOMETOWN_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_HOMETOWN (SOURCE_ID);
CREATE INDEX USER_INSIGHT_HOMETOWN_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_HOMETOWN (KEYWORD);
CREATE INDEX USER_INSIGHT_HOMETOWN_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_HOMETOWN (STATUS);
CREATE INDEX USER_INSIGHT_HOMETOWN_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_HOMETOWN (IS_DELETE);
CREATE INDEX USER_INSIGHT_HOMETOWN_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_HOMETOWN (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_HOMETOWN"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_HOMETOWN a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_HOMETOWN"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'HOMETOWN' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_HOMETOWN_LOCATION a
INNER JOIN "F9_STG_INSIGHT".FACEBOOK_USER_HOMETOWN b ON a.SOURCE_ID = b.DATA;
/*END F9_STG_INSIGHT USER_INSIGHT_HOMETOWN*/


/*BEGIN F9_STG_INSIGHT USER_INSIGHT_LOCATION*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_LOCATION";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_LOCATION"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_LOCATION" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_LOCATION_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LOCATION (REF_ID);
CREATE INDEX USER_INSIGHT_LOCATION_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LOCATION (SOURCE_ID);
CREATE INDEX USER_INSIGHT_LOCATION_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LOCATION (KEYWORD);
CREATE INDEX USER_INSIGHT_LOCATION_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LOCATION (STATUS);
CREATE INDEX USER_INSIGHT_LOCATION_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LOCATION (IS_DELETE);
CREATE INDEX USER_INSIGHT_LOCATION_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_LOCATION (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_LOCATION"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'LOCATION' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_HOMETOWN_LOCATION a
INNER JOIN "F9_STG_INSIGHT".FACEBOOK_USER_LOCATION b ON a.SOURCE_ID = b.DATA;
/*END F9_STG_INSIGHT USER_INSIGHT_LOCATION*/

/*BEGIN F9_STG_INSIGHT USER_INSIGHT_NATION*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_NATION";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_NATION"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_NATION" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_NATION_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_NATION (REF_ID);
CREATE INDEX USER_INSIGHT_NATION_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_NATION (SOURCE_ID);
CREATE INDEX USER_INSIGHT_NATION_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_NATION (KEYWORD);
CREATE INDEX USER_INSIGHT_NATION_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_NATION (STATUS);
CREATE INDEX USER_INSIGHT_NATION_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_NATION (IS_DELETE);
CREATE INDEX USER_INSIGHT_NATION_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_NATION (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_NATION"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_NATION a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;
/*END F9_STG_INSIGHT USER_INSIGHT_NATION*/

/*BEGIN F9_STG_INSIGHT USER_INSIGHT_REGILION*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_REGILION";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_REGILION"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_REGILION" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_REGILION_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_REGILION (REF_ID);
CREATE INDEX USER_INSIGHT_REGILION_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_REGILION (SOURCE_ID);
CREATE INDEX USER_INSIGHT_REGILION_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_REGILION (KEYWORD);
CREATE INDEX USER_INSIGHT_REGILION_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_REGILION (STATUS);
CREATE INDEX USER_INSIGHT_REGILION_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_REGILION (IS_DELETE);
CREATE INDEX USER_INSIGHT_REGILION_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_REGILION (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_REGILION"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_REGILION a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;
/*END F9_STG_INSIGHT USER_INSIGHT_REGILION*/

/*BEGIN F9_STG_INSIGHT USER_INSIGHT_SCHOOL_1*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_1";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_1"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_1" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_SCHOOL_1_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_1 (REF_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_1_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_1 (SOURCE_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_1_FACEBOOK_REF_CITY_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_1 (REF_CITY_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_1_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_1 (KEYWORD);
CREATE INDEX USER_INSIGHT_SCHOOL_1_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_1 (STATUS);
CREATE INDEX USER_INSIGHT_SCHOOL_1_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_1 (IS_DELETE);
CREATE INDEX USER_INSIGHT_SCHOOL_1_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_1 (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_1"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_1 a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_1"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'EDUCATION' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_1 a
INNER JOIN "F9_STG_INSIGHT".FACEBOOK_USER_EDUCATION b ON a.SOURCE_ID = b.GROUP_ID;
/*END F9_STG_INSIGHT USER_INSIGHT_SCHOOL_1*/

/*BEGIN F9_STG_INSIGHT USER_INSIGHT_SCHOOL_2*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_2";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_2"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_2" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_SCHOOL_2_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_2 (REF_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_2_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_2 (SOURCE_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_2_FACEBOOK_REF_CITY_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_2 (REF_CITY_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_2_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_2 (KEYWORD);
CREATE INDEX USER_INSIGHT_SCHOOL_2_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_2 (STATUS);
CREATE INDEX USER_INSIGHT_SCHOOL_2_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_2 (IS_DELETE);
CREATE INDEX USER_INSIGHT_SCHOOL_2_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_2 (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_2"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_2 a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_2"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'EDUCATION' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_2 a
INNER JOIN "F9_STG_INSIGHT".FACEBOOK_USER_EDUCATION b ON a.SOURCE_ID = b.GROUP_ID;
/*END F9_STG_INSIGHT USER_INSIGHT_SCHOOL_2*/

/*BEGIN F9_STG_INSIGHT USER_INSIGHT_SCHOOL_3*/
DROP TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_3";
CREATE TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_3"  (
    "REF_ID" INTEGER NOT NULL , 
    "REF_NAME" VARCHAR(1000 OCTETS),
    "REF_CITY_ID" INTEGER NOT NULL , 
    "REF_CITY_NAME" VARCHAR(1000 OCTETS),
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "SOURCE_NAME" VARCHAR(1000 OCTETS),
    "KEYWORD" VARCHAR(1000 OCTETS) NOT NULL,
    "STATUS" INTEGER , 
    "IS_DELETE" INTEGER,
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL,
	"TYPE" VARCHAR(15 OCTETS) NOT NULL
  ) COMPRESS YES STATIC DISTRIBUTE BY HASH("FACEBOOK_ID") IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_3" ADD PRIMARY KEY  ("REF_ID","SOURCE_ID","KEYWORD","FACEBOOK_ID","TYPE") ENFORCED ;
CREATE INDEX USER_INSIGHT_SCHOOL_3_LANGUAGES_REF_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_3 (REF_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_3_FACEBOOK_SOURCE_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_3 (SOURCE_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_3_FACEBOOK_REF_CITY_ID_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_3 (REF_CITY_ID);
CREATE INDEX USER_INSIGHT_SCHOOL_3_FACEBOOK_KEYWORD_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_3 (KEYWORD);
CREATE INDEX USER_INSIGHT_SCHOOL_3_FACEBOOK_STATUS_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_3 (STATUS);
CREATE INDEX USER_INSIGHT_SCHOOL_3_FACEBOOK_IS_DELETE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_3 (IS_DELETE);
CREATE INDEX USER_INSIGHT_SCHOOL_3_FACEBOOK_TYPE_IDX ON F9_STG_INSIGHT.USER_INSIGHT_SCHOOL_3 (TYPE);

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_3"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'GROUP' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_GROUP_SCHOOL_3 a
INNER JOIN "F9_APP_INSIGHT".USER_GROUP b ON a.SOURCE_ID = b.GROUP_ID;

INSERT INTO "F9_STG_INSIGHT"."USER_INSIGHT_SCHOOL_3"
select REF_ID,REF_NAME,SOURCE_ID,SOURCE_NAME,a.KEYWORD,0,0,b.FACEBOOK_ID,'EDUCATION' from F9_STG_INSIGHT.FACEBOOK_INSIGHT_EDUCATION_SCHOOL_3 a
INNER JOIN "F9_STG_INSIGHT".FACEBOOK_USER_EDUCATION b ON a.SOURCE_ID = b.GROUP_ID;
/*END F9_STG_INSIGHT USER_INSIGHT_SCHOOL_3*/