
/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_HOMETOWN*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_HOMETOWN"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL, 
    "SOURCE_NAME" VARCHAR(1000 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW  NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_HOMETOWN" ADD PRIMARY KEY ("FACEBOOK_ID") ENFORCED ;
CREATE INDEX FACEBOOK_STG_USER_HOMETOWN_DATA_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_HOMETOWN (SOURCE_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_HOMETOWN*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_LOCATION*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_LOCATION"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL, 
    "SOURCE_NAME" VARCHAR(1000 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW  NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_LOCATION" ADD PRIMARY KEY ("FACEBOOK_ID") ENFORCED ;
CREATE INDEX FACEBOOK_USER_LOCATION_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_LOCATION (SOURCE_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_LOCATION*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_LANGUAGES*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_LANGUAGES"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL, 
    "SOURCE_NAME" VARCHAR(1000 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW  NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_LANGUAGES" ADD PRIMARY KEY ("FACEBOOK_ID","SOURCE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_STG_USER_LANGUAGES_DATA_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_LANGUAGES (SOURCE_ID);
CREATE INDEX FACEBOOK_STG_USER_LANGUAGES_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_LANGUAGES (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_LANGUAGES*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_EDUCATION*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_EDUCATION"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL, 
    "SOURCE_NAME" VARCHAR(1000 OCTETS) NOT NULL, 
    "TYPE" VARCHAR(50 OCTETS), 
    "ID" VARCHAR(20 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_EDUCATION" ADD PRIMARY KEY ("FACEBOOK_ID","SOURCE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_USER_EDUCATION_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_EDUCATION (SOURCE_ID);
CREATE INDEX FACEBOOK_USER_EDUCATION_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_EDUCATION (FACEBOOK_ID);
CREATE INDEX FACEBOOK_USER_EDUCATION_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_EDUCATION (TYPE);
CREATE INDEX FACEBOOK_USER_EDUCATION_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_EDUCATION (ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_EDUCATION*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_WORK*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_WORK"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "SOURCE_ID" VARCHAR(20 OCTETS) NOT NULL, 
    "SOURCE_NAME" VARCHAR(1000 OCTETS) NOT NULL, 
    "POSITION_ID" VARCHAR(20 OCTETS), 
    "POSITION_NAME" VARCHAR(1000 OCTETS), 
    "START_DATE" VARCHAR(20 OCTETS), 
    "END_DATE" VARCHAR(20 OCTETS), 
    "ID" VARCHAR(20 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_WORK" ADD PRIMARY KEY ("FACEBOOK_ID","SOURCE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_USER_WORK_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_WORK (SOURCE_ID);
CREATE INDEX FACEBOOK_USER_WORK_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_WORK (FACEBOOK_ID);
CREATE INDEX FACEBOOK_USER_WORK_POSITION_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_WORK (POSITION_ID);
CREATE INDEX FACEBOOK_USER_WORK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_WORK (ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_WORK*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_PAGE*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_PAGE"  (
    "PAGE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "NAME" VARCHAR(1000 OCTETS),
    "CATEGORY" VARCHAR(1000 OCTETS), 
    "CATEGORY_ID" VARCHAR(20 OCTETS), 
    "CREATED_TIME" VARCHAR(50 OCTETS), 
    "TEXT_SEARCH" VARCHAR(1000 OCTETS) 
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("PAGE_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_PAGE" ADD PRIMARY KEY ("PAGE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_PAGE_CATEGORY_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_PAGE (CATEGORY_ID);
CREATE INDEX FACEBOOK_PAGE_TEXT_SEARCH_IDX ON F9_STG_INSIGHT.FACEBOOK_PAGE (TEXT_SEARCH);
CREATE INDEX FACEBOOK_PAGE_NAME_IDX ON F9_STG_INSIGHT.FACEBOOK_PAGE (NAME);
/*END F9_STG_INSIGHT FACEBOOK_PAGE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_GROUP*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_GROUP"  (
    "GROUP_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "NAME" VARCHAR(1000 OCTETS),
    "PRIVACY" VARCHAR(20 OCTETS), 
    "TEXT_SEARCH" VARCHAR(1000 OCTETS) 
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("GROUP_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_GROUP" ADD PRIMARY KEY ("GROUP_ID") ENFORCED ;
CREATE INDEX FACEBOOK_GROUP_PRIVACY_IDX ON F9_STG_INSIGHT.FACEBOOK_GROUP (PRIVACY);
CREATE INDEX FACEBOOK_GROUP_TEXT_SEARCH_IDX ON F9_STG_INSIGHT.FACEBOOK_GROUP (TEXT_SEARCH);
CREATE INDEX FACEBOOK_GROUP_NAME_IDX ON F9_STG_INSIGHT.FACEBOOK_GROUP (NAME);
/*END F9_STG_INSIGHT FACEBOOK_GROUP*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_WORK*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_WORK"  (
    "WORK_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "NAME" VARCHAR(1000 OCTETS),
    "TEXT_SEARCH" VARCHAR(1000 OCTETS) 
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("WORK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_WORK" ADD PRIMARY KEY ("WORK_ID") ENFORCED ;
CREATE INDEX FACEBOOK_WORK_TEXT_SEARCH_IDX ON F9_STG_INSIGHT.FACEBOOK_WORK (TEXT_SEARCH);
CREATE INDEX FACEBOOK_GROUP_NAME_IDX ON F9_STG_INSIGHT.FACEBOOK_WORK (NAME);
/*END F9_STG_INSIGHT FACEBOOK_WORK*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_GROUP*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_GROUP"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "GROUP_ID" varchar(20 OCTETS) NOT NULL)   
   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID",  "GROUP_ID") IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_GROUP" ADD PRIMARY KEY("FACEBOOK_ID","GROUP_ID") ENFORCED ;
CREATE INDEX FACEBOOK_USER_GROUP_GROUP_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_GROUP (GROUP_ID);
CREATE INDEX FACEBOOK_USER_GROUP_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_GROUP (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_GROUP*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_PAGE*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_PAGE";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_PAGE"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "PAGE_ID" varchar(20 OCTETS) NOT NULL)   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_PAGE" ADD PRIMARY KEY ("FACEBOOK_ID","PAGE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_USER_PAGE_PAGE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_PAGE (PAGE_ID);
CREATE INDEX FACEBOOK_USER_PAGE_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_PAGE (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_PAGE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_SOURCE*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_SOURCE";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_SOURCE"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "SOURCE_ID" varchar(20 OCTETS) NOT NULL,
    "TYPE" varchar(20 OCTETS) NOT NULL
  )
   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW  ;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_SOURCE" ADD PRIMARY KEY ("FACEBOOK_ID","SOURCE_ID","TYPE") ENFORCED ;
CREATE INDEX FACEBOOK_USER_SOURCE_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_SOURCE (SOURCE_ID);
CREATE INDEX FACEBOOK_USER_SOURCE_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_SOURCE (FACEBOOK_ID);
CREATE INDEX FACEBOOK_USER_SOURCE_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_SOURCE (TYPE);
CREATE INDEX FACEBOOK_USER_SOURCE_SOURCE_ID_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_SOURCE (SOURCE_ID,TYPE);
/*END F9_STG_INSIGHT FACEBOOK_USER_SOURCE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_LOCATION*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_LOCATION"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "DATA" VARCHAR(20 OCTETS) NOT NULL, 
    "DATA_NAME" VARCHAR(1000 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_LOCATION" ADD PRIMARY KEY ("FACEBOOK_ID") ENFORCED ;
CREATE INDEX FACEBOOK_STG_USER_LOCATION_DATA_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_LOCATION (DATA);
CREATE INDEX FACEBOOK_STG_USER_LOCATION_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_LOCATION (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_LOCATION*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_LANGUAGES*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_LANGUAGES"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "DATA" VARCHAR(20 OCTETS) NOT NULL, 
    "DATA_NAME" VARCHAR(1000 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_LANGUAGES" ADD PRIMARY KEY ("FACEBOOK_ID","DATA") ENFORCED ;
CREATE INDEX FACEBOOK_STG_USER_LANGUAGES_DATA_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_LANGUAGES (DATA);
CREATE INDEX FACEBOOK_STG_USER_LANGUAGES_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_LANGUAGES (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_LANGUAGES*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_EDUCATION*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_EDUCATION"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "DATA" VARCHAR(20 OCTETS) NOT NULL, 
    "DATA_NAME" VARCHAR(1000 OCTETS) NOT NULL, 
    "TYPE" VARCHAR(50 OCTETS), 
    "ID" VARCHAR(20 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_EDUCATION" ADD PRIMARY KEY ("FACEBOOK_ID","DATA") ENFORCED ;
CREATE INDEX FACEBOOK_STG_USER_EDUCATION_DATA_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_EDUCATION (DATA);
CREATE INDEX FACEBOOK_STG_USER_EDUCATION_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_EDUCATION (FACEBOOK_ID);
CREATE INDEX FACEBOOK_STG_USER_EDUCATION_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_EDUCATION (TYPE);
CREATE INDEX FACEBOOK_STG_USER_EDUCATION_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_EDUCATION (ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_EDUCATION*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_WORK*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_WORK"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "DATA" VARCHAR(20 OCTETS) NOT NULL, 
    "DATA_NAME" VARCHAR(1000 OCTETS) NOT NULL, 
    "POSITION_ID" VARCHAR(20 OCTETS), 
    "POSITION_NAME" VARCHAR(1000 OCTETS), 
    "START_DATE" VARCHAR(20 OCTETS), 
    "END_DATE" VARCHAR(20 OCTETS), 
    "ID" VARCHAR(20 OCTETS) NOT NULL
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_WORK" ADD PRIMARY KEY ("FACEBOOK_ID","DATA") ENFORCED ;
CREATE INDEX FACEBOOK_STG_USER_WORK_DATA_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_WORK (DATA);
CREATE INDEX FACEBOOK_STG_USER_WORK_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_WORK (FACEBOOK_ID);
CREATE INDEX FACEBOOK_STG_USER_WORK_POSITION_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_WORK (POSITION_ID);
CREATE INDEX FACEBOOK_STG_USER_WORK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_WORK (ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_WORK*/


/*BEGIN F9_STG_INSIGHT FACEBOOK_PAGE*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_PAGE"  (
    "PAGE_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "NAME" VARCHAR(1000 OCTETS),
    "CATEGORY" VARCHAR(1000 OCTETS), 
    "CATEGORY_ID" VARCHAR(20 OCTETS), 
    "CREATED_TIME" VARCHAR(50 OCTETS), 
    "TEXT_SEARCH" VARCHAR(1000 OCTETS) 
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("PAGE_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_PAGE" ADD PRIMARY KEY ("PAGE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_PAGE_CATEGORY_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_PAGE (CATEGORY_ID);
CREATE INDEX FACEBOOK_PAGE_TEXT_SEARCH_IDX ON F9_STG_INSIGHT.FACEBOOK_PAGE (TEXT_SEARCH);
CREATE INDEX FACEBOOK_PAGE_NAME_IDX ON F9_STG_INSIGHT.FACEBOOK_PAGE (NAME);
/*END F9_STG_INSIGHT FACEBOOK_PAGE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_GROUP*/
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_GROUP"  (
    "GROUP_ID" VARCHAR(20 OCTETS) NOT NULL , 
    "NAME" VARCHAR(1000 OCTETS),
    "PRIVACY" VARCHAR(20 OCTETS), 
    "TEXT_SEARCH" VARCHAR(1000 OCTETS) 
  )   COMPRESS YES STATIC  DISTRIBUTE BY HASH("GROUP_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_GROUP" ADD PRIMARY KEY ("GROUP_ID") ENFORCED ;
CREATE INDEX FACEBOOK_GROUP_PRIVACY_IDX ON F9_STG_INSIGHT.FACEBOOK_GROUP (PRIVACY);
CREATE INDEX FACEBOOK_GROUP_TEXT_SEARCH_IDX ON F9_STG_INSIGHT.FACEBOOK_GROUP (TEXT_SEARCH);
CREATE INDEX FACEBOOK_GROUP_NAME_IDX ON F9_STG_INSIGHT.FACEBOOK_GROUP (NAME);
/*END F9_STG_INSIGHT FACEBOOK_PAGE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_PAGE*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_PAGE";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_PAGE"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "PAGE_ID" varchar(20 OCTETS) NOT NULL)   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_PAGE" ADD PRIMARY KEY ("FACEBOOK_ID","PAGE_ID") ENFORCED ;
CREATE INDEX FACEBOOK_USER_PAGE_PAGE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_PAGE (PAGE_ID);
CREATE INDEX FACEBOOK_USER_PAGE_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_PAGE (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_PAGE*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_GROUP*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_GROUP";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_GROUP"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "GROUP_ID" varchar(20 OCTETS) NOT NULL)   
   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID",  "GROUP_ID") IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_GROUP" ADD PRIMARY KEY("FACEBOOK_ID","GROUP_ID") ENFORCED ;
CREATE INDEX FACEBOOK_USER_GROUP_GROUP_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_GROUP (GROUP_ID);
CREATE INDEX FACEBOOK_USER_GROUP_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_GROUP (FACEBOOK_ID);
/*END F9_STG_INSIGHT FACEBOOK_USER_GROUP*/

/*BEGIN F9_STG_INSIGHT FACEBOOK_USER_SOURCE*/
DROP TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_SOURCE";
CREATE TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_SOURCE"  (
    "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
    "SOURCE_ID" varchar(20 OCTETS) NOT NULL,
    "TYPE" varchar(20 OCTETS) NOT NULL
  )   
   COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1"  ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FACEBOOK_USER_SOURCE" ADD PRIMARY KEY ("FACEBOOK_ID","SOURCE_ID","TYPE") ENFORCED ;
CREATE INDEX FACEBOOK_USER_SOURCE_SOURCE_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_SOURCE (SOURCE_ID);
CREATE INDEX FACEBOOK_USER_SOURCE_FACEBOOK_ID_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_SOURCE (FACEBOOK_ID);
CREATE INDEX FACEBOOK_USER_SOURCE_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_SOURCE (TYPE);
CREATE INDEX FACEBOOK_USER_SOURCE_SOURCE_ID_TYPE_IDX ON F9_STG_INSIGHT.FACEBOOK_USER_SOURCE (SOURCE_ID,TYPE);
/*END F9_STG_INSIGHT FACEBOOK_USER_SOURCE*/


/*BEGIN F9_STG_INSIGHT FRIEND_LOCATION*/
DROP TABLE "F9_STG_INSIGHT"."FRIEND_LOCATION";
CREATE TABLE "F9_STG_INSIGHT"."FRIEND_LOCATION"  (
		  "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
		  "LOCATION_ID" INTEGER NOT NULL , 
		  "LOCATION_NAME" VARCHAR(255 OCTETS) , 
		  "TOWN_ID" INTEGER , 
		  "TOWN_NAME" VARCHAR(255 OCTETS) , 
		  "DOMAIN_ID" INTEGER , 
		  "DOMAIN_NAME" VARCHAR(255 OCTETS) )   
		 COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FRIEND_LOCATION" ADD PRIMARY KEY ("FACEBOOK_ID")	ENFORCED ;
CREATE INDEX FRIEND_LOCATION_LOCATION_ID_IDX ON "F9_STG_INSIGHT"."FRIEND_LOCATION" (LOCATION_ID);
CREATE INDEX FRIEND_LOCATION_TOWN_ID_IDX ON "F9_STG_INSIGHT"."FRIEND_LOCATION" (TOWN_ID);
CREATE INDEX FRIEND_LOCATION_DOMAIN_ID_IDX ON "F9_STG_INSIGHT"."FRIEND_LOCATION" (DOMAIN_ID);
/*END F9_STG_INSIGHT FRIEND_LOCATION*/

/*BEGIN F9_STG_INSIGHT FRIEND_HOMETOWN*/
DROP TABLE "F9_STG_INSIGHT"."FRIEND_HOMETOWN";
CREATE TABLE "F9_STG_INSIGHT"."FRIEND_HOMETOWN"  (
		  "FACEBOOK_ID" VARCHAR(15 OCTETS) NOT NULL , 
		  "HOMETOWN_ID" INTEGER NOT NULL , 
		  "HOMETOWN_NAME" VARCHAR(255 OCTETS) , 
		  "TOWN_ID" INTEGER , 
		  "TOWN_NAME" VARCHAR(255 OCTETS) , 
		  "DOMAIN_ID" INTEGER , 
		  "DOMAIN_NAME" VARCHAR(255 OCTETS) )   
		 COMPRESS YES STATIC  DISTRIBUTE BY HASH("FACEBOOK_ID")   IN "USERSPACE1" ORGANIZE BY ROW NOT LOGGED INITIALLY;
ALTER TABLE "F9_STG_INSIGHT"."FRIEND_HOMETOWN" ADD PRIMARY KEY ("FACEBOOK_ID")	ENFORCED ;
CREATE INDEX FRIEND_HOMETOWN_HOMETOWN_ID_IDX ON "F9_STG_INSIGHT"."FRIEND_HOMETOWN" (HOMETOWN_ID);
CREATE INDEX FRIEND_HOMETOWN_TOWN_ID_IDX ON "F9_STG_INSIGHT"."FRIEND_HOMETOWN" (TOWN_ID);
CREATE INDEX FRIEND_HOMETOWN_DOMAIN_ID_IDX ON "F9_STG_INSIGHT"."FRIEND_HOMETOWN" (DOMAIN_ID);
/*END F9_STG_INSIGHT FRIEND_HOMETOWN*/
