SELECT a.FACEBOOK_ID,a.GENDER,a.NAME,a.USERNAME,a.BIRTHDAY, AGE + 1 AGE
,a.RELATIONSHIP_STATUS,SCHOOL_1_NAME,SCHOOL_2_NAME,SCHOOL_3_NAME,COLLEGE_NAME,COMPANY_NAME,NATION_NAME
,REGILION_NAME,JOB_NAME
,HOMETOWN_NAME,LOCATION_NAME,LANGUAGE_NAME
FROM (
SELECT * FROM USER_PROFILE_ALL WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN')
) a
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct concat(concat(SCHOOL_1_NAME,' - '),SCHOOL_1_CITY_NAME)) SCHOOL_1_NAME FROM USER_SCHOOL_1 
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) b ON a.FACEBOOK_ID = b.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct concat(concat(SCHOOL_2_NAME,' - '),SCHOOL_2_CITY_NAME)) SCHOOL_2_NAME FROM USER_SCHOOL_2 
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) c ON a.FACEBOOK_ID = c.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct concat(concat(SCHOOL_3_NAME,' - '),SCHOOL_3_CITY_NAME)) SCHOOL_3_NAME FROM USER_SCHOOL_3 
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) d ON a.FACEBOOK_ID = d.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct COLLEGE_NAME) COLLEGE_NAME FROM USER_COLLEGE
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) e ON a.FACEBOOK_ID = e.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct COMPANY_NAME) COMPANY_NAME FROM MQT_USER_COMPANY
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) g ON a.FACEBOOK_ID = g.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct NATION_NAME) NATION_NAME FROM MQT_USER_NATION
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) h ON a.FACEBOOK_ID = h.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct REGILION_NAME) REGILION_NAME FROM MQT_USER_REGILION
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) i ON a.FACEBOOK_ID = i.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct JOB_NAME) JOB_NAME FROM MQT_USER_JOB
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) j ON a.FACEBOOK_ID = j.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct LANGUAGE_NAME) LANGUAGE_NAME FROM MQT_USER_LANGUAGES
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) m ON a.FACEBOOK_ID = m.FACEBOOK_ID
LEFT JOIN (
SELECT FACEBOOK_ID, listagg(distinct PARENT_NAME) PARENT_NAME FROM USER_PARENT
	WHERE FACEBOOK_ID IN (SELECT FACEBOOK_ID FROM F9_APP_INSIGHT.USER_MOBILE_TEMP WHERE TYPE = '2019_02_26_TUAN') 
	GROUP BY FACEBOOK_ID
) n ON a.FACEBOOK_ID = n.FACEBOOK_ID
LEFT JOIN USER_AGE_ALL f ON a.FACEBOOK_ID = f.FACEBOOK_ID
LEFT JOIN F9_APP_INSIGHT.USER_HOMETOWN_ALL k ON a.FACEBOOK_ID = k.FACEBOOK_ID
LEFT JOIN F9_APP_INSIGHT.USER_LOCATION_ALL l ON a.FACEBOOK_ID = l.FACEBOOK_ID