UPDATE F9_STG_INSIGHT.REF_CITY 
SET HOMETOWN_GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_HOMETOWN_ALL WHERE HOMETOWN_ID = ID);
UPDATE F9_STG_INSIGHT.REF_CITY 
SET LOCATION_GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_LOCATION_ALL WHERE LOCATION_ID = ID);

UPDATE F9_STG_INSIGHT.REF_COLLEGE 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_COLLEGE WHERE COLLEGE_ID = ID);

UPDATE F9_STG_INSIGHT.REF_COMPANY 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_COMPANY WHERE COMPANY_ID = ID);

UPDATE F9_STG_INSIGHT.REF_COMPANY_BLOCK 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_COMPANY WHERE COMPANY_BLOCK_ID = ID);

UPDATE F9_STG_INSIGHT.REF_COMPANY_FIELD 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_COMPANY WHERE FIELD_ID = ID);

UPDATE F9_STG_INSIGHT.REF_COMPANY_SCALE 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_COMPANY WHERE SCALE_ID = ID);

UPDATE F9_STG_INSIGHT.REF_GENDER 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_GENDER WHERE GENDER = ID);

UPDATE F9_STG_INSIGHT.REF_INCOME 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_INCOME_RULE_APP WHERE INCOME_ID = ID);

UPDATE F9_STG_INSIGHT.REF_INTEREST 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_INTEREST WHERE INTEREST_ID = ID);

UPDATE F9_STG_INSIGHT.REF_JOB 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_JOB WHERE JOB_ID = ID);

UPDATE F9_STG_INSIGHT.REF_LANGUAGES 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_LANGUAGES WHERE LANGUAGE_ID = ID);


UPDATE F9_STG_INSIGHT.REF_NATION 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_NATION WHERE NATION_ID = ID);


UPDATE F9_STG_INSIGHT.REF_RANK 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_INSIGHT_RANK WHERE RANK_ID = ID AND TYPE = 'POSITION');


UPDATE F9_STG_INSIGHT.REF_REGILION 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.MQT_USER_REGILION WHERE REGILION_ID = ID);

UPDATE F9_STG_INSIGHT.REF_RELATIONSHIP_STATUS 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_RELATIONSHIP_STATUS WHERE RELATIONSHIP_STATUS = ID);

UPDATE F9_STG_INSIGHT.REF_SCHOOL_1 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_SCHOOL_1 WHERE SCHOOL_1_ID = ID);

UPDATE F9_STG_INSIGHT.REF_SCHOOL_2 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_SCHOOL_2 WHERE SCHOOL_2_ID = ID);

UPDATE F9_STG_INSIGHT.REF_SCHOOL_3 
SET GLOBAL = (SELECT count(*) FROM F9_APP_INSIGHT.USER_SCHOOL_3 WHERE SCHOOL_3_ID = ID);






